### PR TITLE
Changed doc link in template

### PR DESCRIPTION
**Pull request by JoopAue**
Changed the doc link in the template to link to /docs/home instead of /

Signed-off-by: Joop Aué joopaue@gmail.com

### CODE REVIEW

**Comment by AlpineMutts** [comment]
:+1:

**Comment by JoopAue** [comment]
https://github.com/jekyll/jekyll/pull/3502

**Comment by AlpineMutts** [comment]
@abouter @mdenhoedt could one of you check this? Please don't merge it though.

**Comment by mdenhoedt** [comment]
:+1:

**Comment by abouter** [comment]
Seems alright :+1:

**Comment by JoopAue** [comment]
Merged: [jekyll#3502](https://github.com/jekyll/jekyll/pull/3502)
image

**Pull request closed without merging**
